// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package com.netty.proto;

public interface StudentResponseListOrBuilder extends
        // @@protoc_insertion_point(interface_extends:com.netty.proto.StudentResponseList)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .com.netty.proto.StudentResponse studentResponse = 1;</code>
     */
    java.util.List<com.netty.proto.StudentResponse>
    getStudentResponseList();

    /**
     * <code>repeated .com.netty.proto.StudentResponse studentResponse = 1;</code>
     */
    com.netty.proto.StudentResponse getStudentResponse(int index);

    /**
     * <code>repeated .com.netty.proto.StudentResponse studentResponse = 1;</code>
     */
    int getStudentResponseCount();

    /**
     * <code>repeated .com.netty.proto.StudentResponse studentResponse = 1;</code>
     */
    java.util.List<? extends com.netty.proto.StudentResponseOrBuilder>
    getStudentResponseOrBuilderList();

    /**
     * <code>repeated .com.netty.proto.StudentResponse studentResponse = 1;</code>
     */
    com.netty.proto.StudentResponseOrBuilder getStudentResponseOrBuilder(
            int index);
}
